[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  BRANCH = "main"
  CONTEXT = "production"
  APPLICATION_MODE = "production"

  NEXT_PUBLIC_REST_API_ENDPOINT = "https://f283d761be42.ngrok-free.app/api"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_12345"
  NEXT_PUBLIC_WEBSITE_URL = "https://735ac9b8a101.ngrok-free.app"
  NEXT_PUBLIC_ADMIN_URL = "https://galileecommerce-admin.vercel.app"

  # i18n
  NEXT_PUBLIC_DEFAULT_LANGUAGE = "en"
  NEXT_PUBLIC_ENABLE_MULTI_LANG = "true"
  NEXT_PUBLIC_AVAILABLE_LANGUAGES = "en,ar,zh,fr,de,he,es"

[[plugins]]
  package = "@netlify/plugin-nextjs"
