[build]
  command = "yarn build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # 🔹 API backend (via ngrok ou ton serveur NestJS)
  NEXT_PUBLIC_REST_API_ENDPOINT = "https://f283d761be42.ngrok-free.app/api"

  # 🔹 Mode de l’application
  APPLICATION_MODE = "production"

  # 🔹 Clé publique Stripe
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_12345"

  # 🔹 URLs frontend & admin
  NEXT_PUBLIC_WEBSITE_URL = "https://735ac9b8a101.ngrok-free.app"
  NEXT_PUBLIC_ADMIN_URL   = "https://galileecommerce-admin.vercel.app"

  # 🔹 Options multi-langues
  NEXT_PUBLIC_ENABLE_MULTI_LANG = "true"
  NEXT_PUBLIC_AVAILABLE_LANGUAGES = "en,ar,zh,fr,de,he,es"
